--Query 1: What proportion of frequent flyers have Gold, Platinum, or Titanium status?  
SELECT 
    TIER_NAME,
    COUNT(PASSENGER_SK) AS PASSENGER_COUNT,
    ROUND(COUNT(PASSENGER_SK) * 100.0 / SUM(COUNT(PASSENGER_SK)) OVER(), 2) AS PROPORTION_PCT
FROM DIM_PASSENGER
WHERE IS_CURRENT = 'A' 
  AND TIER_NAME IN ('Gold', 'Platinum', 'Titanium')
GROUP BY TIER_NAME;s

-- Query 2: How often do frequent flyers upgrade?  
SELECT 
    p.TIER_NAME,
    COUNT(f.FLIGHT_ACTIVITY_ID) AS TOTAL_FLIGHTS,
    SUM(f.IS_UPGRADED) AS TOTAL_UPGRADES,
    ROUND(SUM(f.IS_UPGRADED) * 100.0 / COUNT(f.FLIGHT_ACTIVITY_ID), 2) AS UPGRADE_RATE_PCT
FROM FACT_FLIGHT_ACTIVITY f
JOIN DIM_PASSENGER p ON f.PASSENGER_SK = p.PASSENGER_SK
WHERE p.TIER_NAME != 'None' -- Assuming 'None' is for non-loyalty members
GROUP BY p.TIER_NAME;

--Query 3: Do frequent flyers respond to special fare promotions?  
SELECT 
    p.TIER_NAME,
    pr.PROMO_NAME,
    COUNT(f.FLIGHT_ACTIVITY_ID) AS TOTAL_BOOKINGS,
    SUM(f.RESPONDED_TO_PROMO) AS PROMO_RESPONSES,
    ROUND(SUM(f.RESPONDED_TO_PROMO) * 100.0 / COUNT(f.FLIGHT_ACTIVITY_ID), 2) AS RESPONSE_RATE_PCT
FROM FACT_FLIGHT_ACTIVITY f
JOIN DIM_PASSENGER p ON f.PASSENGER_SK = p.PASSENGER_SK
JOIN DIM_PROMOTION pr ON f.PROMOTION_SK = pr.PROMOTION_SK
WHERE pr.PROMO_ID != -1 -- Excluding flights without promotions
GROUP BY p.TIER_NAME, pr.PROMO_NAME;


SELECT * FROM FACT_FLIGHT_ACTIVITY f
JOIN DIM_PASSENGER p ON f.PASSENGER_SK = p.PASSENGER_SK
JOIN DIM_PROMOTION pr ON f.PROMOTION_SK = pr.PROMOTION_SK
--Query 4: How long are their overnight stays?  
SELECT 
    p.TIER_NAME,
    AVG(f.OVERNIGHT_STAY_NIGHTS) AS AVG_STAY_DURATION_NIGHTS,
    MAX(f.OVERNIGHT_STAY_NIGHTS) AS MAX_STAY_DURATION_NIGHTS
FROM FACT_FLIGHT_ACTIVITY f
JOIN DIM_PASSENGER p ON f.PASSENGER_SK = p.PASSENGER_SK
WHERE f.OVERNIGHT_STAY_NIGHTS > 0
GROUP BY p.TIER_NAME;

--Query 5: Analyze company profit through multiple reservation channels  
SELECT 
    c.CHANNEL_NAME,
    c.CHANNEL_TYPE,
    SUM(f.FINAL_TICKET_AMOUNT_USD) AS TOTAL_REVENUE,
    SUM(f.EST_FLIGHT_COST_ALLOCATION) AS TOTAL_COST,
    SUM(f.PROFIT_MARGIN_USD) AS TOTAL_PROFIT
FROM FACT_RESERVATION_FINANCES f
JOIN DIM_CHANNEL c ON f.CHANNEL_SK = c.CHANNEL_SK
GROUP BY c.CHANNEL_NAME, c.CHANNEL_TYPE
ORDER BY TOTAL_PROFIT DESC;

--Query 6: Analyze customer care interaction type and problem severity  
SELECT 
    i.INTERACTION_TYPE,
    i.SEVERITY,
    COUNT(c.CUSTOMER_CARE_ID) AS TOTAL_ISSUES,
    AVG(c.RESOLUTION_TIME_DAYS) AS AVG_RESOLUTION_DAYS,
    AVG(c.CSAT_SCORE) AS AVG_CUSTOMER_SATISFACTION
FROM FACT_CUSTOMER_CARE c
JOIN DIM_INTERACTION i ON c.INTERACTION_SK = i.INTERACTION_SK
GROUP BY i.INTERACTION_TYPE, i.SEVERITY
ORDER BY TOTAL_ISSUES DESC;


